# Création de Tensors

In [1]:
import torch

# Tensor 0D (Scalaire)

scalar = torch.tensor(42)
print("Tensor 0D (Scalaire) :", scalar)

# Tensor 1D (Vecteur)
vector = torch.tensor([1, 2, 3, 4, 5])
print("Tensor 1D (Vecteur) :", vector)

# Tensor 2D (Matrice)
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Tensor 2D (Matrice) :\n", matrix)

# Tensor 3D
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("Tensor 3D :\n", tensor_3d)

Tensor 0D (Scalaire) : tensor(42)
Tensor 1D (Vecteur) : tensor([1, 2, 3, 4, 5])
Tensor 2D (Matrice) :
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Tensor 3D :
 tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])


# Types de Données et Précision

In [2]:
# Tensor avec type de données spécifié
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print("Float Tensor (32-bit) :", float_tensor)

double_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
print("Double Tensor (64-bit) :", double_tensor)

int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
print("Integer Tensor (32-bit) :", int_tensor)

Float Tensor (32-bit) : tensor([1., 2., 3.])
Double Tensor (64-bit) : tensor([1., 2., 3.], dtype=torch.float64)
Integer Tensor (32-bit) : tensor([1, 2, 3], dtype=torch.int32)


# Tensors Spéciaux et Initialisation

In [5]:
# Tensor de zéros
zeros = torch.zeros(3, 4)
print("Tensor de zéros :\n", zeros)

# Tensor de uns
ones = torch.ones(2, 3)
print("Tensor de uns :\n", ones)

# Tensor avec valeurs aléatoires uniformes entre 0 et 1
random_uniform = torch.rand(2, 2)
print("Tensor aléatoire uniforme :\n", random_uniform)

# Tensor avec valeurs aléatoires suivant une distribution normale
random_normal = torch.randn(2, 2)
print("Tensor aléatoire normal :\n", random_normal)

# Tensor avec une séquence de nombres
arange = torch.arange(start=0, end=20)
print("Tensor avec séquence :", arange)

Tensor de zéros :
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Tensor de uns :
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor aléatoire uniforme :
 tensor([[0.6989, 0.7589],
        [0.9436, 0.3885]])
Tensor aléatoire normal :
 tensor([[-0.9084, -1.2987],
        [-0.6018, -2.3066]])
Tensor avec séquence : tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
